### ISSUE TITLE
Error when consuming in TypeScript project

### ISSUE THREAD

**Issue by chnn** [zapier/intl-dateformat#5]
Hello,

I'm trying to consume intl-dateformat from a TypeScript project. When I compile the project with `tsc`, I see an error:

```
$ tsc --noEmit --pretty
node_modules/intl-dateformat/lib/index.d.ts:15:39 - error TS2307: Cannot find module './types'.

15 export declare const _default: import("./types").FormatFunction;
                                         ~~~~~~~~~


Found 1 error.
```

I had to add `"skipLibCheck": true` to my project `tsconfig.json` to workaround this.

I noticed that in the build process for intl-dateformat, the following warning is logged from `dts-bundle-generator`:

```
BEWARE: The generated file could not be properly checked due enabled "skipLibCheck" compiler option
```

Perhaps relevant?

**Comment by ngryman** [comment]
Hey thanks for reporting.

It seems that `dts-bundle-generator` is trying to import a file that doesn't exist in `lib/`. I created a new branch where I only rely on `tsc` to generate type definitions. Would you mind testing this branch?

You can reference it like this in your `package.json` and then run `(yarn|npm) install`:

```json
{
  "dependencies": {
    "intl-dateformat": "zapier/intl-dateformat#fix/4"
  }
}
```

**Comment by chnn** [comment]
@ngryman That branch fixes the issue for me. Thanks!
